### ISSUE TITLE
Create Kibana Demo App

### ISSUE THREAD

**Issue by stormpython** [elastic/phoenix#1]
To demonstrate the features of this visualization library, a demo app in Kibana needs to be created. This app would look like something similar to [chart.js](http://www.chartjs.org/docs/#bar-chart-introduction) or [highchart.js](http://www.highcharts.com/demo).

**Comment by tsullivan** [comment]
Could a Docker container be leveraged for this?

**Comment by panda01** [comment]
Here is a start.
https://github.com/elastic/kibana-phoenix-plugin

**Comment by stormpython** [comment]
I am closing this issue, since this app has been created. It will need more work but we can move issues for that into that repo which is here: https://github.com/elastic/kibana-phoenix-plugin
